### ISSUE TITLE
Can you give a Example of web scraping for following url? 

### ISSUE THREAD

**Issue by subodhcjoshi82** [whimtrip/jwht-scrapper#1]
Hi
With the help your API how to extract data from the following url?
https://www.icicidirect.com/idirectcontent/Research/TechnicalAnalysis.aspx/companyprofile/inftec

mainly i need table data. Second thing in same session or after this url call how to get data from other url which you can find left hand side of this Page?

**Comment by Louis-wht** [comment]
Hello, 

Glad you found my scrapper to help your scrapping purpose! 

For your first question, you need two basic steps : 
- First creating the POJO on which you will map the extracted data, see [here](https://github.com/whimtrip/jwht-htmltopojo#how-to-use--basics) for more detail.
- Secondly, you need to build and configure your scrapper helper class until the scrapping works as expected (you'll probably have some problems while scrapping if this website applies some scrapping protections which you can override using the different features proposed by this API). To build your own scrapper helper, see [here](https://github.com/whimtrip/jwht-scrapper#build-your-scrapper-helper).
- Finally, just [build and run your scrapper client](https://github.com/whimtrip/jwht-scrapper#lets-scrap)


For your second question, you should read this [part of the documentation](https://github.com/whimtrip/jwht-scrapper#links). This built in feature will allow you to follow the links you can find on the left of the page so that you can properly scrap the other pages as well in other POJOs classes.

Please let me know if it is clear or not, and if something sounds unclear, I'd like to know why so that I can update the documentation accordingly.

Thanks!
